name: user_repository
description: The repo that handle users
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.4.0-220.0.dev <4.0.0"

dependencies:
  cloud_firestore: ^4.15.9
  equatable: ^2.0.5
  firebase_auth: ^4.17.9
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
