// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr5H-JNHKaVpTNdyv_veH4LOzl6F6HmW0',
    appId: '1:647619451163:web:3a5116c9898533dfa81bbe',
    messagingSenderId: '647619451163',
    projectId: 'loginapp-a7459',
    authDomain: 'loginapp-a7459.firebaseapp.com',
    storageBucket: 'loginapp-a7459.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEJqpre3Pkvvm6EzFM38Sl9pwXqgBKp4k',
    appId: '1:647619451163:android:573d91fc82a35fd6a81bbe',
    messagingSenderId: '647619451163',
    projectId: 'loginapp-a7459',
    storageBucket: 'loginapp-a7459.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1E5u2qh9kpuXQ0yOR2rrm6ZfwJkEOiPk',
    appId: '1:647619451163:ios:76d0cd7f35d1618ca81bbe',
    messagingSenderId: '647619451163',
    projectId: 'loginapp-a7459',
    storageBucket: 'loginapp-a7459.appspot.com',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1E5u2qh9kpuXQ0yOR2rrm6ZfwJkEOiPk',
    appId: '1:647619451163:ios:e0dd333c86703ba2a81bbe',
    messagingSenderId: '647619451163',
    projectId: 'loginapp-a7459',
    storageBucket: 'loginapp-a7459.appspot.com',
    iosBundleId: 'com.example.loginApp.RunnerTests',
  );
}
